### ISSUE TITLE
destination middleware

### ISSUE THREAD

**Issue by luizcarlospedrosogomes** [ui5-community/ui5-ecosystem-showcase#563]
run localhost
using default-env.json
#ERROR#/Handler#####502a7f64-9d39-4035-b728-0c91380b4064####4XmEGeuFIC7ToSuhMa2Ja9dANzlXxseC######kz1nqn75#PLAIN##GET request to /screencontrol/api/scm_fv/HomeECommerce/create completed with status 500 Cannot read property 'tokenType' of undefined#

but run in portal or launchpad service without errors

**Comment by petermuessig** [comment]
Hi @luizcarlospedrosogomes ,

I assume you mean an issue related to `ui5-middleware-cfdestination`? 

To me the error is coming from the server with the status code `500`. There the server tries to access the property `tokenType` which is not set. When running in a portal or launchpad, there are credentials set (`tokens`). But this issue could also be related to the `AppRouter`. Can you please attach a stacktrace to understand the error in more detail? Right now, it is hard for me to guess, where the error appears.

Thanks and best regards,
Peter

**Comment by luizcarlospedrosogomes** [comment]
Hi @petermuessig 

yes,  ui5-middleware-cfdestination.

How to add stacktrace?

I used cf logs apps but the request does not arrive at the api linked to destination.

**Comment by luizcarlospedrosogomes** [comment]
![image](https://user-images.githubusercontent.com/9791364/151784307-35d866c3-1573-4242-b4ff-c69b620433b7.png)
I have this error, which for me is normal, I open the router app link and I have this other error. remembering that this destination is not authenticated.

xs-app.json
`{
  "authenticationMethod": "route",
  "welcomeFile": "/index.html",
  "routes": [
    {
      "source": "^/user-api(.*)",
      "target": "$1",
      "service": "sap-approuter-userapi"
    }
    ,{
      "source": "^/screencontrol/(.*)$",
      "target": "$1",
      "destination": "screencontrol"
      
    }
    ,{
      "destination": "SPROSalesAppOdata",
      "source": "^/SPROSalesAppOdata/(.*)$",      
      "target": "$1"
    }    
    ,{
      "source": "^(.*)",
      "target": "$1",      
      "service": "html5-apps-repo-rt"
    }
  ]  
}`

**Comment by petermuessig** [comment]
in the stacktrace above, it tries to do some SAML auth - but this doesn't work for XHR requests. How is the destination configured? I am no real expert with the cf destination handling, but this is what I can see. Maybe the following blog helps: https://blogs.sap.com/2018/12/11/cloud-foundry-authentication-how-it-works-step-by-step/ 

Is it maybe necessary to add the `"authenticationType": "xsuaa",` to the `screencontrol` destination?

Cc: @vobu

**Comment by luizcarlospedrosogomes** [comment]
configuration destination screencontrol
![image](https://user-images.githubusercontent.com/9791364/151841381-fdcd201c-1d75-4556-a188-00d7c4e05128.png)

add "authenticationType": "xsuaa" but error continue.

**Comment by petermuessig** [comment]
Shouldn't in the destination configuration also an authentication be configured? I am not sure about that and what should be configured here. As long as there is NoAuthentication, the XHR tries to do SAML authentication, which can't work.

**Comment by luizcarlospedrosogomes** [comment]
log
```
#2.0#2022 02 02 09:31:27:353#-03:00#INFO#/approuter#####kz5j3uwi##########kz5j3uwi#PLAIN##Application router is listening on port: 5000#
Server started
URL: http://localhost:8080
{
  err: Error: Request failed with status code 401
      at createError (D:\TRABALHO\SPRO\SPRO\produtos\comercial\SALESFORCE_UI_UI5\node_modules\axios\lib\core\createError.js:16:15)
      at settle (D:\TRABALHO\SPRO\SPRO\produtos\comercial\SALESFORCE_UI_UI5\node_modules\axios\lib\core\settle.js:17:12)
      at IncomingMessage.handleStreamEnd (D:\TRABALHO\SPRO\SPRO\produtos\comercial\SALESFORCE_UI_UI5\node_modules\axios\lib\adapters\http.js:312:11)
      at IncomingMessage.emit (events.js:388:22)
      at endReadableNT (internal/streams/readable.js:1336:12)
      at processTicksAndRejections (internal/process/task_queues.js:82:21) {
    config: {
      transitional: [Object],
      adapter: [Function: httpAdapter],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 5000,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      headers: [Object],
      withCredentials: true,
      maxRedirects: 0,
      url: 'https://sprohanacloudsub.authentication.us10.hana.ondemand.com/oauth/token',
      method: 'post',
      data: 'grant_type=client_credentials&response_type=token&client_id=sb-dafa3193-1f8b-441f-921f-142fa9aa3960%21b22482%7Chtml5-apps-repo-uaa%21b424&client_secret=c91f14b1-641e-4ef5-8eda-b02f60d2bbea%248lc48uyw5FcrFIbehwOZ94d6icw1HFVO6DC6x7_LWUg%3D'
    },
    request: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 237,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'POST /oauth/token HTTP/1.1\r\n' +
        'Accept: application/json\r\n' +
        'Content-Type: application/x-www-form-urlencoded\r\n' +
        'User-Agent: nodejs-xssec-3\r\n' +
        'x-vcap-request-id: aa5d8418-2b21-443c-82f6-037a8508312d\r\n' +
        'Content-Length: 237\r\n' +
        'Host: sprohanacloudsub.authentication.us10.hana.ondemand.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/oauth/token',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: [Function: emitRequestTimeout],
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'sprohanacloudsub.authentication.us10.hana.ondemand.com',
      protocol: 'https:',
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    response: {
      status: 401,
      statusText: 'Unauthorized',
      headers: [Object],
      config: [Object],
      request: [ClientRequest],
      data: [Object]
    },
    isAxiosError: true,
    toJSON: [Function: toJSON]
  },
  accessToken: undefined,
  expiration: undefined,
  tokenType: undefined,
  serviceName: 'html5-apps-repo-rt',
  subaccount: undefined,
  correlationId: 'aa5d8418-2b21-443c-82f6-037a8508312d'
}
Feb 02, 2022 09:31:28 AM D:\TRABALHO\SPRO\SPRO\produtos\comercial\SALESFORCE_UI_UI5\node_modules\@sap\approuter\lib\utils\token-utils.js [kz5j3vhj] ERROR: Error getting client_credentials token for html5-apps-repo-rt from subaccount undefined errorRequest failed with status code 401
info server:custommiddleware:cfdestination proxying GET /SPROSalesAppOdata/v2/lib/xsodata/service.xsodata/$metadata?sap-language=PT to http://localhost:5000/SPROSalesAppOdata/v2/lib/xsodata/service.xsodata/$metadata?sap-language=PT...
REQUEST {
  uri: 'http://localhost:5000/SPROSalesAppOdata/v2/lib/xsodata/service.xsodata/$metadata?sap-language=PT',
  callback: undefined
}
REQUEST make request http://localhost:5000/SPROSalesAppOdata/v2/lib/xsodata/service.xsodata/$metadata?sap-language=PT
#2.0#2022 02 02 09:31:28:567#-03:00#INFO#/Auth/OAuth2#####71811de5-e285-4fe3-a046-3d346d8a168a####Mx9CDTPOcjFUPQF47Nby3soDztcN9zN1######kz5j3vvx#PLAIN##query does not exist for request url /SPROSalesAppOdata/v2/lib/xsodata/service.xsodata/$metadata?sap-language=PT#
#2.0#2022 02 02 09:31:28:568#-03:00#INFO#/Auth/OAuth2#####71811de5-e285-4fe3-a046-3d346d8a168a####Mx9CDTPOcjFUPQF47Nby3soDztcN9zN1######kz5j3vvx#PLAIN##sending page with client-side redirect to https://sprohanacloudsub.authentication.us10.hana.ondemand.com/oauth/authorize?response_type=code&client_id=sb-forcavendas-authentication!t22482&redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Flogin%2Fcallback#
#2.0#2022 02 02 09:31:28:569#-03:00#INFO#/Auth/OAuth2#####71811de5-e285-4fe3-a046-3d346d8a168a####Mx9CDTPOcjFUPQF47Nby3soDztcN9zN1######kz5j3vvx#PLAIN##x-forwarded-path header: undefined#
REQUEST onRequestResponse http://localhost:5000/SPROSalesAppOdata/v2/lib/xsodata/service.xsodata/$metadata?sap-language=PT 200 {
  'x-request-id': 'kz5j3vvx',
  'x-frame-options': 'SAMEORIGIN',
  'cache-control': 'no-cache, no-store, must-revalidate',
  'content-type': 'text/html',
  'content-security-policy': "script-src 'self' 'unsafe-inline'; frame-ancestors *",
  date: 'Wed, 02 Feb 2022 12:31:28 GMT',
  connection: 'keep-alive',
  'content-length': '642'
}
REQUEST finish init function http://localhost:5000/SPROSalesAppOdata/v2/lib/xsodata/service.xsodata/$metadata?sap-language=PT
REQUEST response end http://localhost:5000/SPROSalesAppOdata/v2/lib/xsodata/service.xsodata/$metadata?sap-language=PT 200 {
  'x-request-id': 'kz5j3vvx',
  'x-frame-options': 'SAMEORIGIN',
  'cache-control': 'no-cache, no-store, must-revalidate',
  'content-type': 'text/html',
  'content-security-policy': "script-src 'self' 'unsafe-inline'; frame-ancestors *",
  date: 'Wed, 02 Feb 2022 12:31:28 GMT',
  connection: 'keep-alive',
  'content-length': '642'
}
info server:custommiddleware:cfdestination proxying GET /user-api/currentUser to http://localhost:5000/user-api/currentUser...
REQUEST {
  uri: 'http://localhost:5000/user-api/currentUser',
  callback: undefined
}
REQUEST make request http://localhost:5000/user-api/currentUser
#2.0#2022 02 02 09:31:28:899#-03:00#ERROR#/Handler#####6701035e-f397-4c55-b45d-f8a8e5652354####VcQEly2xizbmXVZ1dh85DId_rYc-7xS5######kz5j3w5e#PLAIN##GET request to /user-api/currentUser completed with status 401 
Authentication required#
REQUEST onRequestResponse http://localhost:5000/user-api/currentUser 401 {
  'x-request-id': 'kz5j3w5e',
  'x-frame-options': 'SAMEORIGIN',
  'cache-control': 'no-cache, no-store, must-revalidate',
  date: 'Wed, 02 Feb 2022 12:31:28 GMT',
  connection: 'keep-alive',
  'transfer-encoding': 'chunked'
}
REQUEST finish init function http://localhost:5000/user-api/currentUser
REQUEST response end http://localhost:5000/user-api/currentUser 401 {
  'x-request-id': 'kz5j3w5e',
  'x-frame-options': 'SAMEORIGIN',
  'cache-control': 'no-cache, no-store, must-revalidate',
  date: 'Wed, 02 Feb 2022 12:31:28 GMT',
  connection: 'keep-alive',
  'transfer-encoding': 'chunked'
}
info server:custommiddleware:cfdestination proxying GET /screencontrol/api/scm_fv/HomeECommerce/create to http://localhost:5000/screencontrol/api/scm_fv/HomeECommerce/create...
REQUEST {
  uri: 'http://localhost:5000/screencontrol/api/scm_fv/HomeECommerce/create',
  callback: undefined
}
REQUEST make request http://localhost:5000/screencontrol/api/scm_fv/HomeECommerce/create
#2.0#2022 02 02 09:31:28:974#-03:00#ERROR#/Handler#####9f3686d8-9043-4bda-bc38-e94c5ca9782d####fMIGN8Cl6riFh4Ikx_C0q5MmjvqfBPtq######kz5j3w7h#PLAIN##GET request to /screencontrol/api/scm_fv/HomeECommerce/create completed with status 401 Authentication required#
REQUEST onRequestResponse http://localhost:5000/screencontrol/api/scm_fv/HomeECommerce/create 401 {
  'x-request-id': 'kz5j3w7h',
  'x-frame-options': 'SAMEORIGIN',
  'cache-control': 'no-cache, no-store, must-revalidate',
  date: 'Wed, 02 Feb 2022 12:31:28 GMT',
  connection: 'keep-alive',
  'transfer-encoding': 'chunked'
}
REQUEST finish init function http://localhost:5000/screencontrol/api/scm_fv/HomeECommerce/create
REQUEST response end http://localhost:5000/screencontrol/api/scm_fv/HomeECommerce/create 401 {
  'x-request-id': 'kz5j3w7h',
  'x-frame-options': 'SAMEORIGIN',
  'cache-control': 'no-cache, no-store, must-revalidate',
  date: 'Wed, 02 Feb 2022 12:31:28 GMT',
  connection: 'keep-alive',
  'transfer-encoding': 'chunked'
}

```

**Comment by luizcarlospedrosogomes** [comment]
I remove service html5-apps-repo-rt in xs-app.json and default-env.json. working  in localhost
