### ISSUE TITLE
[ui5-tooling-transpile] Exception produced during plugin execution when babel.config contains plugins

### ISSUE THREAD

**Issue by sam-garland** [ui5-community/ui5-ecosystem-showcase#810]
**Describe the bug**
There is an issue in `ui5-tooling-transpile` version 3.0.4 (not present in 3.0.3) when used with a `babel.config` that includes plugin definitions.

Given this `babel.config`:
```
{
  "ignore": [
    "**/*.d.ts"
  ],
  "plugins": [
    "@babel/plugin-transform-strict-mode"
  ],
  "presets": [
    "transform-ui5",
    [
      "@babel/preset-typescript",
      {
        "allowDeclareFields": true
      }
    ]
  ],
  "sourceMaps": true
}
```

We are getting the following error:

```
[2023-08-25T03:42:12.321Z] [karma-cov-ci:module:configurator           ] /data/jenkins/workspace/anch_development_ui-apps_PR-2106/node_modules/karma-ui5-transpile/lib/index.js:74

[2023-08-25T03:42:12.321Z] [karma-cov-ci:module:configurator           ] 				return plugin.file.request === "istanbul";

[2023-08-25T03:42:12.321Z] [karma-cov-ci:module:configurator           ] 				              ^

[2023-08-25T03:42:12.321Z] [karma-cov-ci:module:configurator           ] 

[2023-08-25T03:42:12.321Z] [karma-cov-ci:module:configurator           ] TypeError: Cannot read properties of undefined (reading 'file')

[2023-08-25T03:42:12.321Z] [karma-cov-ci:module:configurator           ]     at /data/jenkins/workspace/anch_development_ui-apps_PR-2106/node_modules/karma-ui5-transpile/lib/index.js:74:19

[2023-08-25T03:42:12.321Z] [karma-cov-ci:module:configurator           ]     at Array.find (<anonymous>)

[2023-08-25T03:42:12.321Z] [karma-cov-ci:module:configurator           ]     at /data/jenkins/workspace/anch_development_ui-apps_PR-2106/node_modules/karma-ui5-transpile/lib/index.js:73:26

[2023-08-25T03:42:12.321Z] [karma-cov-ci:module:configurator           ] 

[2023-08-25T03:42:12.321Z] [karma-cov-ci:module:configurator           ] Node.js v18.16.0

[2023-08-25T03:42:12.321Z] [karma-cov-ci:module:sap.via.shared         ] /data/jenkins/workspace/anch_development_ui-apps_PR-2106/node_modules/karma-ui5-transpile/lib/index.js:74

[2023-08-25T03:42:12.321Z] [karma-cov-ci:module:sap.via.shared         ] 				return plugin.file.request === "istanbul";

[2023-08-25T03:42:12.321Z] [karma-cov-ci:module:sap.via.shared         ] 				              ^

[2023-08-25T03:42:12.321Z] [karma-cov-ci:module:sap.via.shared         ] 

[2023-08-25T03:42:12.321Z] [karma-cov-ci:module:sap.via.shared         ] TypeError: Cannot read properties of undefined (reading 'file')

[2023-08-25T03:42:12.321Z] [karma-cov-ci:module:sap.via.shared         ]     at /data/jenkins/workspace/anch_development_ui-apps_PR-2106/node_modules/karma-ui5-transpile/lib/index.js:74:19

[2023-08-25T03:42:12.321Z] [karma-cov-ci:module:sap.via.shared         ]     at Array.find (<anonymous>)

[2023-08-25T03:42:12.321Z] [karma-cov-ci:module:sap.via.shared         ]     at /data/jenkins/workspace/anch_development_ui-apps_PR-2106/node_modules/karma-ui5-transpile/lib/index.js:73:26

[2023-08-25T03:42:12.321Z] [karma-cov-ci:module:sap.via.shared         ] 

[2023-08-25T03:42:12.321Z] [karma-cov-ci:module:sap.via.shared         ] Node.js v18.16.0

[2023-08-25T03:42:12.321Z] [karma-cov-ci:module:configurator           ] npm ERR! Lifecycle script `karma-cov-ci` failed with error: 

[2023-08-25T03:42:12.321Z] [karma-cov-ci:module:configurator           ] npm ERR! Error: command failed 

[2023-08-25T03:42:12.321Z] [karma-cov-ci:module:configurator           ] npm ERR!   in workspace: configurator@3.14.16 

[2023-08-25T03:42:12.321Z] [karma-cov-ci:module:configurator           ] npm ERR!   at location: /data/jenkins/workspace/anch_development_ui-apps_PR-2106/configurator 

[2023-08-25T03:42:12.321Z] [karma-cov-ci:module:sap.via.shared         ] npm ERR! Lifecycle script `karma-cov-ci` failed with error: 

[2023-08-25T03:42:12.321Z] [karma-cov-ci:module:sap.via.shared         ] npm ERR! Error: command failed 

[2023-08-25T03:42:12.321Z] [karma-cov-ci:module:sap.via.shared         ] npm ERR!   in workspace: sap.via.shared@3.14.16 

[2023-08-25T03:42:12.321Z] [karma-cov-ci:module:sap.via.shared         ] npm ERR!   at location: /data/jenkins/workspace/anch_development_ui-apps_PR-2106/sap.via.shared 

[2023-08-25T03:42:12.321Z] [karma-cov-ci:module:configurator           ] 

[2023-08-25T03:42:12.321Z] [karma-cov-ci:module:configurator           ] > sap.via.applications@3.14.16 karma-cov-ci:module:configurator

[2023-08-25T03:42:12.321Z] [karma-cov-ci:module:configurator           ] > npm run karma-cov-ci -w configurator
```

The following code in `babel-core` is creating a babel config with `plugins` and `presets` fields that have a type of  `ConfigItem[]`:

https://github.com/babel/babel/blob/e43d8e77cf88245e930055e70a42f46e2996bce6/packages/babel-core/src/config/partial.ts#L119

https://github.com/babel/babel/blob/e43d8e77cf88245e930055e70a42f46e2996bce6/packages/babel-core/src/config/item.ts#L9

When `normalizePresetOrPlugin` is passed a `ConfigItem` in the `babelPresetOrPlugin` argument, it returns the `ConfigItem` object that was passed in (in other cases a string identifying a module that can be passed into `require.resolve()` is returned):
https://github.com/ui5-community/ui5-ecosystem-showcase/blob/9127d611a58bd7677bff96480f652f4eeea53172/packages/ui5-tooling-transpile/lib/util.js#L116

This  results in a `ConfigItem` being passed as the `moduleName` argument to `resolveNodeModule`: 
https://github.com/ui5-community/ui5-ecosystem-showcase/blob/9127d611a58bd7677bff96480f652f4eeea53172/packages/ui5-tooling-transpile/lib/util.js#L24C10-L24C27

Both invokations of `require.resolve()` return `undefined` as the `request` argument is expected to contain a string rather than an object, meaning `resolveNodeModule` returns `undefined`.

This results in `babelOptions.plugins` containing an array of length 1 containing an `undefined` value, which causes the exception at:
https://github.com/ui5-community/ui5-ecosystem-showcase/blob/9127d611a58bd7677bff96480f652f4eeea53172/packages/karma-ui5-transpile/lib/index.js#L73

**To Reproduce**

Use a babel.config with some plugins defined (see above) with the 
ui5-tooling-transpile plugin.

The issue was occurring when running tests using a `package.json` containing the following `devDepenendencies`:

```jsonc
  "devDependencies": {
    "@babel/plugin-transform-strict-mode": "7.22.5",
    "@sapui5/types": "1.116.0",
    "@types/web": "0.0.114",
    "@ui5/builder": "3.0.9",
    "@ui5/cli": "3.4.0",
    "@ui5/fs": "3.0.4",
    "@ui5/ts-interface-generator": "0.7.0",
    "adm-zip": "0.5.10",
    "http-proxy-middleware": "2.0.6",
    "jsonc-parser": "3.2.0",
    "karma": "6.4.2",
    "karma-chrome-launcher": "3.2.0",
    "karma-coverage": "2.2.1",
    "karma-junit-reporter": "2.0.1",
    "karma-sinon": "1.0.5",
    "karma-sonarqube-generic-reporter": "1.0.0",
    "karma-sourcemap-loader": "0.4.0",
    "karma-ui5": "3.0.3",
    "karma-ui5-transpile": "3.1.1",
    "local-web-server": "5.3.0",
    "lodash.merge": "4.6.2",
    "minimatch-all": "1.1.0",
    "mvn-artifact-download": "6.1.1",
    "npm-run-all": "4.1.5",
    "rimraf": "5.0.1",
    "sinon": "15.2.0",
    "ts-standard": "12.0.2",
    "typescript": "5.1.6"
  },
```

The issue does not occur when `"ui5-tooling-transpile": "3.0.3",` is added.

This has been observed when running karma tests on a UI5 project using TypeScript.
I can provide a link to the actual project (accessible within SAP) if there are issues with reproducing the issue.

**Expected behavior**

The observed exception should not occur as the `babel.config` file is valid according to the babel documentation.

**Environment**

This is not related to the OS, node version etc.

**Comment by petermuessig** [comment]
Good catch, @sam-garland - I will have a look.

**Comment by petermuessig** [comment]
@sam-garland - from a first look to understand this issue, I would assume the following:

The babel plugin/preset cannot be resolved and then undefined is returned as the name of the plugin/preset in the function `resolvePresetOrPlugin`:

https://github.com/ui5-community/ui5-ecosystem-showcase/blob/9127d611a58bd7677bff96480f652f4eeea53172/packages/ui5-tooling-transpile/lib/util.js#L152-L158

This code is executed before babel is used to load the config:

https://github.com/ui5-community/ui5-ecosystem-showcase/blob/9127d611a58bd7677bff96480f652f4eeea53172/packages/ui5-tooling-transpile/lib/util.js#L55-L60

To deactivate the resolve of the tooling extension you can set the configuration option `skipBabelPresetPluginResolve` in the configuration section of the extension in the `ui5.yaml` to `true`. This then restores the old behavior and let babel resolve the plugins. You can try this and see whether it works again? 

One option I see is a fail-safe fallback in the normalization to keep the string when the plugin/preset can't be resolved (see the `||` after the `resolveNodeModule` call):

```js
	// => in case of the preset/plugin cannot be resolved, we return just
	//    use the given preset/plugin name and let babel do the resolve
	//    which may lead to issues in pnpm or global ui5 tooling scenarios (rare cases!)
	if (Array.isArray(babelPresetOrPlugin)) {
		const normalized = normalizePresetOrPlugin(babelPresetOrPlugin[0], isPreset);
		babelPresetOrPlugin[0] = resolveNodeModule(normalized, cwd) || babelPresetOrPlugin[0];
	} else if (typeof babelPresetOrPlugin === "string") {
		const normalized = normalizePresetOrPlugin(babelPresetOrPlugin, isPreset);
		babelPresetOrPlugin = resolveNodeModule(normalized, cwd) || babelPresetOrPlugin;
	}
```

This ensures that either the fully resolved path or the string is available as preset/plugin and no `undefined` can be in there.

**Comment by petermuessig** [comment]
@sam-garland : should be fixed with the following versions:

* `ui5-tooling-transpile`: `3.2.0`
* `karma-ui5-transpile`: `3.2.0`

Thanks for the catch and helping to improve the tooling extensions!
